class Locators:

    page_URL = "https://www.selenium.dev/documentation/webdriver/"

    xpath_locator_logo = "//*[@id='Layer_1']"
    css_locator_logo = "#Layer_1"
    xpath_locator_header_menu = "//*[@id='main_navbar']"
    css_locator_header_menu = "#main_navbar"
    xpath_locator_search = "//*[@class='DocSearch-Button-Placeholder']"
    css_locator_search = ".DocSearch-Button-Placeholder"
    xpath_locator_left_side_bar = "//div/nav/ul"
    css_locator_left_side_bar = "div>nav>ul"
    xpath_locator_main_content = "//body//div/main/div"
    css_locator_main_content = "body div>main>div"
    xpath_locator_main_content_title = "//body//div/main/div/h1"
    css_locator_main_content_title = "body div>main>div>h1"
    xpath_locator_about_button = "//*[starts-with(@id, 'navbar')]"
    css_locator_about_button = "[id$='navbar']"
    xpath_locator_alert_heading = "//*[contains(@class, 'text-center m-0')]"
    css_locator_alert_heading = "[class*='text-center m-0']"
    xpath_locator_download_button = "(//*[@class='nav-link'])[1]"
    css_locator_download_button = "[class*='nav-item mr-4 mb-2 mb-lg-0']:nth-child(3)"
    xpath_locator_selenium_in_twitter_button = "(//footer/div/div/div/ul/li)[2]"
    css_locator_selenium_in_twitter_button = "footer>div>div>div:first-of-type>ul>li:nth-child(2)"
    xpath_locator_projects_button = "//*[@href='/projects']"
    xpath_locator_page = "/html"
    xpath_locator_browser_stack_link = "//*[@alt='BrowserStack']"
    xpath_locator_sauce_labs_link = "//*[@src='/images/sponsors/saucelabs.png']"
    xpath_locator_text_footer = "//small[text()='© 2023 Software Freedom Conservancy All Rights Reserved']"
    xpath_locator_sponsors_section_title = "//h2[contains(text(), 'Sponsors')]"
    xpath_locator_getting_started_button = "//a[starts-with(text(), 'Getting')]"
    xpath_locator_blog_button = "//span[text()='Blog']"
    xpath_locator_youtube_link = "//*[@class='fab fa-youtube']"
    xpath_locator_browsers_button = "//*[@id='m-documentationwebdriverbrowsers']"
    xpath_locator_troubleshooting_button = "//*[@title='Troubleshooting Assistance']"
    xpath_locator_recommendation_button = "//*[@href='https://www.w3.org/TR/webdriver1/']"
    xpath_locator_waits_button = "//*[@id='m-documentationwebdriverwaits']"
    xpath_locator_elements_button = "//span[text()='Elements']"
    xpath_locator_print_button = "//*[@id='print']"
    xpath_locator_create_issue_button = "//*[text()=' Create project issue']"
    xpath_locator_create_documentation_issue_button = "//*[text()=' Create documentation issue']"
    xpath_locator_facebook_link = "//*[@class='fab fa-facebook']"
    xpath_locator_create_support_features_button = "//a[text()='Support features']"
    xpath_locator_selenium_version_text = "//*[@class='ml-auto mx-3 fw-bold']"
